ALKY:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 5000
AMON:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 1500
CNDC_CTD:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 5
CPHL:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 150
DEPH:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 4000
DOXY_BTL:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 12
DOXY_CTD:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 12
H2S:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 2000
HUMUS:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 100
NTOT:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 1500
NTRA:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 300
NTRI:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 20
NTRZ:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 350
PRES_CTD:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 1000
SALT_BTL:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 36
SALT_CTD:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 36
TEMP_BTL:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: -1
    max_range_value: 24
TEMP_CTD:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: -1
    max_range_value: 24
TOC:
  global: !!python/object:fyskemqc.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 10
